### ISSUE TITLE
wrap up Milestone v1.82 - what's left to finish

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#142]
@scotthibbs @ct7aup @tekenny  @f6fvy @Yagi-Berra 

Hi all,
I think we are getting close to completing the goals for [Milestone v1.82](https://github.com/w7sst/MorseRunner/milestone/2). We talked about fixing a few bugs, adding ARRL DX Contest, and improving introduction materials. I think these items have been completed.

We also had a goal to announce to a larger user community. I was initially thinking of an announcement to the N1MM user group since I had [mentioned to them](https://groups.io/g/N1MMLoggerPlus/topic/92010360#70513) back in early summer that I was working on this. I wanted to announce to them using the same discussion topic when we are ready.

However, we have to be sure we are ready to support this announcement. I'd like to use this Issue as a discussion area to agree we are ready for an larger announcement. I'm hoping to pull back from development activities for the next 6-8 weeks, but will be available for discussions.

So let's start a discussion below (in the comments) and update the following TASK list as needed to work out the remaining details for the v1.82 release.

## Pre-release testing
Here is a zip file of the latest build: https://nextcloud.brashlerphoto.com/s/MicQNZdFNcsk6zq

## Remaining Tasks
- [x] finish code review and merge ARRL DX Contest
- [x] finish code review and merge Update Contest Scoring
- [x] implement and review `Help | First Time Setup`.
- [x] Release notes and `readme.txt` file (Scott)
- [x] Wait for ARRL response
- [x] builds (Mike)
- [x] #164
- [x] decide where we are going to announce. Perhaps we only announce in one place for v1.82. We can announce future versions in other places.
- [x] Work with @tekenny to complete new developer onboarding instructions. He has written a new [DEVELOPERS.md](https://github.com/w7sst/MorseRunner/blob/main/.github/DEVELOPERS.md) page, but it is not yet linked from the main readme.md page. Mike updated the `readme.md` file to reference Tom's `DEVELOPERS.md` page. this is pending a review by @tekenny .
- [x] others??? - please click Edit above and update this list. Mark off items as you complete them.

**Comment by w7sst** [comment]
I have updated the pre-release version. This build contains all Issues that are currently in code review. Please download the updated zip file: https://nextcloud.brashlerphoto.com/s/MicQNZdFNcsk6zq

@tekenny @ct7aup @f6fvy @scotthibbs @DF9TS @n2ic @jr8ppg @jm1dxh @K6OK

**Comment by K6OK** [comment]
I tested the build as both a domestic and DX station:

1TT or 100 are shown as entered in the Edit3 box and in the log.  ✓
ENN accepted for both domestic and DX in Edit4 box.  ✓

With KL7AA (DX) as runner, does not accept 5NN ATT, Aoo, A00 or NN as valid exchanges in Edit4 box.  

With K6OK (domestic) as runner, does not reject an invalid state/province (i.e., ZZ or KW) in Edit4 box.  It rejects 1TT and 100, but not KW or K.

**Comment by w7sst** [comment]
Thank you for testing both domestic and DX sides of this contest. I appreciate it.

1. I updated regular expressions for ATT, Aoo, A00 or NN. Also allow them to be entered into exchange fields. This regex is now: `'([0-9]*)|(K)|(KW)|([0-9A]*[OTN]*)'`.
2. For the domestic runner case above, I did changed the regular expression for states/provinces to expect two characters making up US state or VE province: `'[ABCDFGHIKLMNOPQRSTUVWY][ABCDEFHIJKLMNORSTUVXYZ]'`. This will reject the 'K' or the 'KW' and accept any valid state or province.

I posted an [updated build](https://nextcloud.brashlerphoto.com/s/MicQNZdFNcsk6zq) for further testing.

**Comment by w7sst** [comment]
I posted an [updated build](https://nextcloud.brashlerphoto.com/s/MicQNZdFNcsk6zq) containing the `Help | First Time Setup`. I think this is all the code changes for 1.82 (pending the discussion regarding the `ARRL.LIST` file).

Please look at the Remaining Tasks at the top of this page. We have the release notes and announcement text remaining. Any help would be welcome. Let's try to get this release announcement completed by 12/12. I will be leaving town on 12/14. Thank you, Mike.

**Comment by w7sst** [comment]
@scotthibbs - I started the draft Release 1.82. next step is release notes and update the readme.txt file. I'll make a review pass after you get these ready.

@tekenny @ct7aup @f6fvy @scotthibbs @DF9TS @n2ic @jr8ppg @jm1dxh @K6OK
We are getting close to releasing 1.82. Please give the release a test drive and test a few contests. Thank you to some of you that have helped with early testing.

Please keep the Remaining Tasks list at the top of this page up to date. Thank you, Mike

**Comment by K6OK** [comment]
- Tested ARRL DX pileup as domestic station with 5NN, ENN.  Works as expected in both Pileup and Single Calls mode, only DX stations call. Exchanges in both directions are correct.  ✓

- Tested ARRL DX pileup as DX station with 5NN, ENN.  Works as expected, only K and VE stations call. Exchanges in both directions are correct. ✓

- Did quick tests of each of the other contests and HST, confirmed they all work as expected. ✓

- First Time Setup launches new form as expected (nice addition to the program, BTW) ✓

- Minor issue: Exchange field for DX stations doesn't reject zero power (user typo error) such as TT or 00.

- Minor comment: If ARRL DX is the contest and Run/WPX Competition is clicked, it proceeds as an ARRL DX contest.  Maybe Run/WPX Competition should be disabled and grayed out?

- Minor comment: should the Prefix column in the Log window be suppressed? It's not relevant to ARRL DX.

**Comment by w7sst** [comment]
@K6OK - thank you for the feedback.
- interesting catch regarding 0 power levels. I like your approach to testing - you focus on boundary conditions and it reminds me of a QA manager I used to work with. :-) I will probably not fix this at this time since the error checking for user input on these cells is currently implemented to length only and constraining to a valid set of characters. If you would like, please add a feature request to improve error checking of bad exchange input (similar to N1MM rules/behavior).
- I created Issue #160 to track removal of the `Pref` column from the screen log.
- I agree that the WPX Competition should be disabled. Scott and I have discussed the idea that perhaps any contest could be run in "competition mode" allowing scoring to be generated for any contest and submitted to a website for comparison against other operators running the same contest.

**Comment by w7sst** [comment]
I uploaded an [updated build](https://nextcloud.brashlerphoto.com/s/MicQNZdFNcsk6zq) containing these latest changes.

**Comment by K6OK** [comment]
Good news -- per my phone call with ARRL, permission is granted to use DXCC.LIST under two conditions
1. MRCE does not market or imply our software is endorsed by ARRL.
2. ARRL requests that we add a header to the top of DXCC.LIST that says "Used with permission: DXCC Country List, copyright ARRL."

**Comment by w7sst** [comment]
I uploaded an [updated build](https://nextcloud.brashlerphoto.com/s/MicQNZdFNcsk6zq) containing these latest changes.

**Comment by w7sst** [comment]
Pending review by @k6ok and @f6fvy, I think we are ready to go.
- I have merged the remaining PRs, rebuilt MR, updated our temporary install image (the zip file) and updated the installation Assets on our [Release 1.82 page](https://github.com/w7sst/MorseRunner/releases).
- If you have a few minutes, download the [latest build](https://nextcloud.brashlerphoto.com/s/MicQNZdFNcsk6zq) and test a few contests.

Thank you for all the effort getting this release ready to go.

**Comment by n2ic** [comment]
Okay, guys, I'm a lid. Just installed Delphi Community Edition. Would like
to try that, instead of Lazarus, which is what I used for the current MR
running with N1MM+. What's the best way to get the 1.82 source, load it
into Delphi, and build it ?

73,
Steve, N2IC

**Comment by K6OK** [comment]
Looks good here.  One comment I have, this can wait until the next release if you want, is to make the default startup settings more friendly to the less advanced CW operator, e.g.:

QSK should be unchecked
All of the band conditions should be unchecked
Default CW speed should be lower than 30 wpm, I'd suggest 25 wpm
With VE3NEA as the default call, then the default exchange should be "ON" not "OR"
Band conditions: it says LID's but should be LIDs.  Possessive apostrophe shouldn't be used here.

As it stands now on first startup the settings might be a little intimidating to a more modest CW op.

Quickly tested all contests with normal exchanges, all seemed OK.

**Comment by w7sst** [comment]
Hi Steve,
Let's point you to our existing documentation for developers. It will be a good opportunity to see if this documentation will answer your questions. Please let us know if it does not or submit changes to fill in the holes.

1. start with our readme page: https://github.com/w7sst/MorseRunner#how-can-i-help
2. You will then see:
> Please refer to [CONTRIBUTING.md](https://github.com/w7sst/MorseRunner/blob/main/.github/CONTRIBUTING.md) for more information. Developers can refer to [DEVELOPERS.md](https://github.com/w7sst/MorseRunner/blob/main/.github/DEVELOPERS.md) for additional on-boarding information and build instructions.

Let us know how it goes from there...

To directly answer your question, you be doing something like the following to clone a copy of our repository onto your local machine:
```
git clone https:github.com/w7sst/MorseRunner MorseRunnerCE
cd MorseRunnerCE
git checkout main
```
Then you can follow the build instructions in DEVELOPERS.md.

**Comment by n2ic** [comment]
Here's what I get loading it into Delphi CE:
[image: image.png]

**Comment by w7sst** [comment]
Steve, the image did not come through, so I don't see your error.

**Comment by w7sst** [comment]
Steve, you may have to use the github.com web page to paste an image. If you are sending the image via email response, it may not work.

**Comment by w7sst** [comment]
> Looks good here. One comment I have, this can wait until the next release if you want, is to make the default startup settings more friendly to the less advanced CW operator, e.g.:
> 
> QSK should be unchecked All of the band conditions should be unchecked Default CW speed should be lower than 30 wpm, I'd suggest 25 wpm With VE3NEA as the default call, then the default exchange should be "ON" not "OR" Band conditions: it says LID's but should be LIDs. Possessive apostrophe shouldn't be used here.
> 
> As it stands now on first startup the settings might be a little intimidating to a more modest CW op.
> 
> Quickly tested all contests with normal exchanges, all seemed OK.

@k6ok, The above changes are in code review. I updated the [latest build](https://nextcloud.brashlerphoto.com/s/MicQNZdFNcsk6zq). Thank you again for the input.

**Comment by w7sst** [comment]
The 1.82 Release has been published. Congrats everyone! Thanks for all the hard work.
