### ISSUE TITLE
Add support for SST Contest

### ISSUE THREAD

**Issue by scotthibbs** [w7sst/MorseRunner#172]
* **Contest Name:** K1USN CW Ops SST Contest
* **Contest Rules:** http://www.k1usn.com/sst.html
* **Call History file name:** https://n1mmwp.hamdocs.com/mmfiles/k1usnsst-074-txt/

Per discussions in MorseRunnerCE@groups.io with Bruce, K1BG who is a CW Academy advisor for Beginners, it was requested to add the SST Contest. 

Members of the K1USN Radio Club, who are also members of the CW Operators’ Club (CWops), run a one-hour slow speed CW “contest,” called the SST. For those who prefer a more leisurely CW pace or are new CW operators or contesters, this just might be what you're looking for!  
Nov. 6th, 2022, US Daylight Savings Time ended
 SST UTC times do not change
Fridays 20:00-21:00 UTC: 3-4pm EST, 12-1pm PST
Mondays 00:00-01:00 UTC: 7-8pm EST, 4-5pm Sunday

### Unique contest behaviors

Bruce, K1BG started the discussion on our MorseRunnerCE@groups.io here: https://groups.io/g/MorseRunnerCE/topic/96270434#14

### Farnsworth:  
In this discussion on groups it was mentioned that Farnsworth is used in this contest which is made for beginners. 
We have previously discussed Farnsworth in our discussions section of GitHub here: 
https://github.com/w7sst/MorseRunner/discussions/114
And basically we decided to not add Farnsworth as this is not a learning Morse program with the sentiment that we maintain the original program's intent to be a contesting simulator. 

But since this contest is a training contest for new operators who are learning utilizing Farnsworth timing, it was decided to add this feature for this contest only. 

### TASKS
- [x] Initial coding for the SST Contest. (w7sst)
- [x] Define format for the call history file (w7sst) - Same format as the N1MM file history file mentioned above.
- [x] Build a suitable call history file from actual logs from the contest. Perhaps Bruce, K1BG, and @k6ok can help put this together.
- [x] If time permits, add a basic Farnworth support for this contest only. Idea is to maintain Farnsworth speed at 20 wpm whenever user selects MR CW Speeds below 25wpm. Speeds above 25wpm will not use Farnsworth spacing - only when MR CW Speed is below 25wpm will the Farnsworth spacing be applied.
- [x] provide a pre-release build (w7sst). [download v1.83-pr3 here](https://nextcloud.brashlerphoto.com/s/LFgw7zS34zGwna3)
- [x] fix any bugs found. (w7sst)
- [x] create pull request and start code review (w7sst)
- [x] integrate pull request (w7sst)
- [x] simplify Exchange and TU reports (reported by Bruce, fixed by w7sst)
- [x] include user's callsign in final TU in SST contest (reported by Bruce, fixed by w7sst)
- [x] after validation, close this issue.
- [x] release notes (@scotthibbs)

### Can you help?
Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, I'm available to discuss questions or alternatives regarding the implementation of this contest.
- [x] Yes, I'd like to review and provide feedback on the proposed solution.
- [x] Yes, I'm available to help test this contest. Let me know when it is ready for early testing.
- [x] Also Bruce, K1BG wished to help with testing this contest as well.

**Comment by w7sst** [comment]
I have posted a review for the SST Contest. I'm finishing up the Farnsworth support for SST contest only. Once complete, I'll post a pre-release build so we can get some early user-testing on this SST Contest with Farnsworth support only. Please let me know if you are interested in helping with early testing.

**Comment by w7sst** [comment]
Reopening this issue so we can give it some testing time.

**Comment by w7sst** [comment]
I have posted MR v1.83-pr2 Pre-Release build [here](https://nextcloud.brashlerphoto.com/s/f5AXikfkTnw7BwM). Please give it a spin and give us your feedback.

**Comment by w7sst** [comment]
Feedback from Bruce @K1BG-Bruce received via email dated 3/8...

> Mike,
>
>Attached is the audio recording of what I am talking about.  7 minutes of MorseRunner, and the ONLY callsign identification is when the station calls CQ.
>
>I hope this doesn’t sound negative.  You are doing great with what you are doing, and I don’t want to come across that way.
>
>I’m not sure why you are sending a pleasantry in SST at the end of the QSO – it’s a contest.  Here is the description of a typical contact from the K1USN SST page:
>
>Pi, K1RV sends:                      CQ SST K1RV
>Rick, N1DC replies with:        N1DC
>Pi, K1RV replies with:            N1DC Pi MA
>Rick, N1DC replies with:        GE Pi Rick MA
>Pi, K1RV: replies with:           GL Rick TU K1RV SST
>
>None of the 73 or “dit dit” at the end.  Typically, TU and Callsign is the ending.  Here is the link to their webpage.  http://www.k1usn.com/sst
>
>I might even argue that there is no need for the “GE Pi” pleasantry (I have never done this is SST or any contest).  But since it’s the sponsor’s recommendation, I’ll accept it.
>
>One thing to keep in mind.  The FCC does say that you should identify at the end of every transmission.  Contesters sometimes stretch this a little.  But the way the software is now, there is only an identification when calling CQ.
>
>I want to check the minimum Farsnworth setting as well, but I am up to my neck in work, ... (removed rest of line).
>
>But on a positive note, I’m very excited and appreciative about what YOU are doing.  What you have done so far is so much better than what we had before.  This is really exciting and I can’t express my gratitude enough.
>
>Bruce, K1BG

**Comment by w7sst** [comment]
I decided to simplify further by eliminating the `<name> <name> <state> <state>` variation of the dual exchange. The remaining exchange is now of the form `<name> <state> <name> <state>` with an optional leading `R`. I chose this form because this is primarily a training contest and a duplicated exchange is most likely to follow the standard exchange order of `<name> <state>`.

I did not update the pre-release build with this last change.

**Comment by K1BG-Bruce** [comment]
Mike,

 

When I click on the link I still get pr2, and it works the same way.

 

Am I missing something?

 

Bruce

**Comment by w7sst** [comment]
Hi Bruce,
Sorry, my bad. Here is the corrected link for my change. I keep learning the details of the tools we are using. Sorry for the confusion.

Path to updated 1.83-pr3.2:  https://nextcloud.brashlerphoto.com/s/LFgw7zS34zGwna3

When you unzip this file, the folder will still say 1.83-pr3, but the executable will show v1.83-pr3.2 on the splash screen.

-Mike

**Comment by w7sst** [comment]
Leaving this open for validation.

**Comment by K1BG-Bruce** [comment]
Mike,

 

I looked at both 1.83-pr3.2 and 1.83-rc1.  These are  vastly better than before.

 

One omission – after the “TU” at the end of a contact, the sending stations callsign should be sent.  I did not hear this in either of these last two revisions.

 

Thanks.

 

Bruce, K1BG

**Comment by w7sst** [comment]
Hi Bruce,
Thank you for your feedback. I will consider adding the callsign after each TU for this contest.

Have you been able to try the Farnsworth timing behavior with the SST Contest? Is this feature/behavior meeting your expectations for this contest as used by your students? We need help validating and closing out #188 .

Thank you,
Mike

**Comment by w7sst** [comment]
Approved by Bruce (see comment in #197)
