### ISSUE TITLE
Exchange Resent After Editing Call

### ISSUE THREAD

**Issue by Stingy49** [w7sst/MorseRunner#177]
### Description
If I get a call wrong during CWOPS CWT (also ARRL FD, haven't tried others), instead of sending the corrected call followed by TU it sends the corrected call followed by my exchange again.

### Steps To Reproduce
1. Start CWOPS CWT
2. Copy a call wrong (ex. K4AD instead of correctly copying K4AB)
3. Fix call when other station sends DE K4AB *name* *nr* along with entering correct name and nr (doesn't matter if text cursor is in the name or nr field)
4. Press enter

#### Expected behavior
You reply with the corrected call and TU. The QSO ends and is logged.

#### Actual Behavior
You reply with the corrected call but then follow with your exchange causing the other station to send their info again unnecessarily.

#### Reproduces how often
100%

### Version information
1.82, 1.81, and 1.80 all exhibit the issue.

### Additional context
Works correctly in 1.68

### Can you help?
Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, I'm available to help test a solution to this problem.

## Tasks
- [x] Post a pre-release build
- [ ] Validate the bug fix

**Comment by w7sst** [comment]
This problem was also reported by John, K3TN, on groups.io. See https://groups.io/g/MorseRunnerCE/topic/difference_in_operating/96249040.

**Comment by w7sst** [comment]
I have posted MR v1.83-pr2 Pre-Release build [here](https://nextcloud.brashlerphoto.com/s/f5AXikfkTnw7BwM). Please reset this bug and comment below after validating the fix.

@Stingy49 @scotthibbs

**Comment by Stingy49** [comment]
@w7sst Works great for me!
