### ISSUE TITLE
All contests - minimal space between sent callsign and exchange

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#194]
### Description
When running any contest, when responding to a DxStation with their callsign, MR will send their callsign followed by your Exchange. In all contests, there is almost no spacing between the callsign and the exchange. My measurements is showing 1-2 units of space. This spacing should be at least 5 units to match the current inter-word spacing between words.

### Steps To Reproduce
1. Choose any contest. For this discussion, choose WPX.
2. Click `Run | Single Calls` to start the contest
3. Enter the DxStation's callsign. Press Enter.
4. You will hear the callsign immediately followed by the exchange.
5. Click `Run` to stop.

**Hint**
- Select `File | Audio Recording Enabled` menu item before starting the contest.
- When you stop the contest, you can go back an listen to the generated CW and slow it down if necessary in your audio playback.
- De-select `File | Audio Recording Enabled` menu item after running it because the state is retained in the .INI file.
- Note: recording the audio is a good technique to keep in mind when trying to understand these issues.

#### Expected behavior
There should be the usual inter-word spacing between the callsign and the exchange. Original MR included about 5 units of spacing between words, where a unit is the space of a single dit. You can hear this 5U spacing in other contests (e.g. in ARRL Field Day, you can hear the spacing between the two parts of the exchange). However, you do not hear the same spacing between the callsign and the start of the exchange.

#### Actual Behavior
What you hear is minimal time between the callsign and the start of the exchange. This is true for all contests. I think this was not noticed in the original MR because the WPX exchange is `5NN<number>` and the 5NN portion is expected in your brain, so we didn't think much of it. If you list to contests on the air, you will often hear a response between the callsign and the start of the exchange.

#### Reproduces how often
~100%, yet our brain may not notice the problem. You can easily hear the problem in the new SST Contest because the exchange begins with the user's name. In this case, your brain cannot separate the callsign from the name since there is insufficient spacing between elements.

### Version information
  - Morse Runner version: all versions. SST version is 1.83-pr2
  - OS/Version: Windows 10

### Additional context
If interested, here are two articles on CW timing:
- https://morsecode.world/international/timing.html
- https://www.arrl.org/files/file/Technology/x9004008.pdf

## TASKS
- [ ] Fix the bug
- [ ] Write up release note
- [ ] Post code review/pull request
- [ ] merge; mark as `fixed - ready for validation`
- [ ] Validation

**Comment by w7sst** [comment]
This bug is the root cause of #193. The initial fix reported in #193 made the problem more obvious and reported by @K3TN.

**Comment by w7sst** [comment]
This bug was fixed by fixing some of the logic used in CW generation.
- 3 units (length of a 'dit') between characters
- 5 units between words (original MR was using 5 units; standard is 7 units).
- ~5 units between messages. Some messages are generated in a sequential manner. In this case, the timing is hard to control, so the length is close to the original 5 units of space between words.

Also updated the math to insure that correct Wpm is generated.
