### ISSUE TITLE
Wrap up Release 1.83

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#197]
Let's target getting our next release wrapped up this month. The main motivation is the CWOPS Training team's desire to use the K1USN SST Contest as part of their training. Also, @jr8ppg has implemented the JARL All Japan and ACAG domestic contests (and I noticed he has announced this on his blog). We need to get these three contests released.

So, please edit the following Task list with items that need to be completed. The big item of course is release notes. Scott will again be the lead for that (I'll pull in the details from github when I create the release and give Scott a chance to do the final edits.

## Tasks
- [x] Generate a pre-release - [download here](https://nextcloud.brashlerphoto.com/s/LFgw7zS34zGwna3). Does not include Release Notes.
- [x] Update version number in release notes. Scott usually names the release, so we'll see what he comes up with.
- [x] Update release notes
- [x] Write section for AllJA and ACAG contests @jr8ppg 
- [x] Write note for K1USN SST Contest (@K1BG-Bruce)
- [x] generate the draft release notes and add the tag (@w7sst)
- [x] generate a final [pre-release (v1.83-rc1)](https://nextcloud.brashlerphoto.com/s/kFw4ZfCSztZzwjC) (@w7sst)
- [x] Add the detail notes from GitHub and provide to Scott. (mike)
- [x] consider a pre-release (Mike)
- [x] Validate and close issue #172 
- [x] Validate and close issue #188 
- [x] Fix DXCC file entry for Kenya (`ARRL.LIST` file)
- [x] fix and validate Issue #201 (this was a last-minute useability fix)
- [x] publish the release (mike)
- [x] announcements?  where and what content?

### Validation
If you are able to give one or more of these a test run using the pre-release build, please mark them off as complete. Thank you...
- [x] ARRL DX
- [x] ARRL Field Day
- [x] CQ WPX
- [x] CQ WW
- [x] CWOPS CWT
- [x] HST (High Speed Test)
- [x] JARL ALL JA
- [x] JARL ACAG
- [x] K1USN Slow Speed Test, including Farnsworth behavior (and close issues #172 and #188)
- [x] NCJ NAQP

**Comment by w7sst** [comment]
I have posted a pre-release, v1.83-pr3 [here](https://nextcloud.brashlerphoto.com/s/LFgw7zS34zGwna3). It does not include Release Note changes. It does contain SST, Farnsworth, JARL All JA and ACAG contests.

@scotthibbs @jr8ppg

**Comment by jr8ppg** [comment]
I wrote a description of the JARL contests.
please Add  to the CONTEST INFORMATION section of the readme.
```
CONTEST INFORMATION
    JARL ALLJA
    The ALLJA Contest is the most major contest in Japan.
    When: Last weekend in April.
    How: Contact as many Prefecture or Hokkaido promotion bureau possible.
    Exchange: RST plus Prefecture code/Hokkaido promotion bureau code plus Power code(P/L/M/H)
    Rules: https://www.jarl.org/Japanese/1_Tanoshimo/1-1_Contest/all_ja/all_ja_rule.htm (japanese only)
           In the JARL contest, a code that means power is added to the end of the exchange number.
           P is 5W or less(QRP), L is 10W or less, M is 100W or less, H is greater than 100W.

    JARL All Cities All Guns(ACAG)
    The ACAG contests have very long exchange numbers.
    When: Two days before the second Monday in October.
    How: Contact as many City or Gun(Country) or Ku(Ward) possible.
    Exchange: RST plus City code/Gun(Country) code/Ku(Ward) code plus Power code(P/L/M/H)
    Rules: https://www.jarl.org/Japanese/1_Tanoshimo/1-1_Contest/all_cg/allcg_rule.htm (japanese only)

```

**Comment by scotthibbs** [comment]
@K1BG-Bruce, I've made this up for the K1USN contest so far. Just an idea, so submit your own or edit this one as you desire. - Scott

K1USN Slow Speed Test (SST)
Members of the K1USN Radio Club, who are also members of the CW Operators’ Club (CWops), run a one-hour slow speed CW “contest,” called the SST. For those who prefer a more leisurely CW pace or are new CW operators or contesters, this just might be what you're looking for! 
When: Fridays 20:00-21:00 UTC & Mondays 00:00-01:00 UTC
How: Slower speeds (up to 20 Words Per Minute). Usually sent with 25wpm character speeds. 
Farnsworth: For this contest only. Character wpm speed can be set by changing the number for "FarnsworthCharacterRate=25" entry in the MorseRunner.ini file found in the install folder and restarting the program. 
Exchange: suggested first name and state, province, or DX country. It is fairly common to send greetings with exhanges. 
Rules, frequencies and sample exhanges can be found at http://www.k1usn.com/sst.html

**Comment by K1BG-Bruce** [comment]
Scott,

 

My suggestions below.

 

THANK YOU FOR HELPING MAKE THIS HAPPEN!

**Comment by scotthibbs** [comment]
Perfect!

**Comment by w7sst** [comment]
@scotthibbs 
Hi Scott, I started the Release Page draft [here](https://github.com/w7sst/MorseRunner/releases/edit/untagged-970426dbd862ab4d6a51). Please edit as you see fit. We also have to update `readme.txt` with new version number, etc.

**Comment by scotthibbs** [comment]
Sweet. Will start tonight.

**Comment by w7sst** [comment]
I have created v1.83-rc1 (release candidate) build [here](https://nextcloud.brashlerphoto.com/s/kFw4ZfCSztZzwjC) for everyone to try. If you have some time over the next week, can you give this a try and validate one or two contests. The full contest list has been included in the TASKS section above. Please mark off the ones you have tested. Scott is working on the final `readme.txt` and updating the release notes. I hope to publish this release by the 25th or so.
Thank you, Mike.

@scotthibbs @ct7aup @jr8ppg @K1BG-Bruce @f6fvy @tekenny @K6OK @WR7Q

**Comment by w7sst** [comment]
I fixed another issue reported by Bruce (send `TU <callsign>` at the end of a QSO). A new release candidate has been upload, [v1.83-rc2](https://nextcloud.brashlerphoto.com/s/GFaDi8ribWNgoYY).

**Comment by WR7Q** [comment]
ARRL Field Day
 CQ WW

 NCJ NAQP
 CWA CWT

I tested these all out and they worked great. 

Thanks so much.

73,
Bob WR7Q
CWA Admin

**Comment by w7sst** [comment]
Hi Bruce @K1BG-Bruce 

We are waiting for a final okay from you for the SST Contest and Farnsworth support. Once approved, I will generate the final build and publish the release.

Thank you for your help.

73,
Mike W7SST

@scotthibbs

**Comment by K1BG-Bruce** [comment]
Mike,

 

I got to it today, and I think we are good-to-go.

 

Thanks again!

 

Bruce

**Comment by w7sst** [comment]
I have published the 1.83 release. Thank you to everyone who contributed to this release.

**Comment by w7sst** [comment]
This release, v1.83, is complete.
