### ISSUE TITLE
Send TU+MyCall after working a pileup

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#247]
## Summary
@f6fvy suggested the following via email:
> To enhance realism, I also suggest to send "TU" + MyCall (instead of 'TU' only) *when* the number of calling stations is 0 (ie we just worked the last station of the pileup).

## Motivation
Enhance realism.

## Additional context
[Mike's additional comments...] I like this idea.
When running in Pile-up or competition modes (probably not HST), we send the user's callsign after working the last station. The simulation would then continue sending CQ until the next station appears. Perhaps after working the next single station, a TU only is sent until the next pile-up actually appears when you have two or more stations calling back. Once there is a pipeup of two or more, then we send "TU <MyCall>" after the last station in this pileup is worked.

## Can you help?
Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, I'm available to discuss possible solutions and alternatives to this problem.
- [x] Yes, I'd like to review and provide feedback on the proposed solution.
- [x] Yes, I'm available to help test a solution to this problem.

## Tasks
- [x] write up a proposal
- [x] review with others
- [ ] coding
- [ ] validation

**Comment by w7sst** [comment]
@f6fvy, Larry commented via email...
> Do you mean the user won't have to hit F1 at all until the next station
appears ? I'm not a fan of these 'auto-CQ' and prefer to keep it under
control.

No, I think your original suggestion here was to send the `TU` followed by `MyCall` one time only. I would probably look at adding a timer so this occurs every 2-5 minutes whenever pile-up count goes to zero.

**Comment by w7sst** [comment]
Feedback from @jr8ppg in Issue #381 ...

> Feedback from JA users.
> 
> In CQWW, there was a station that only sent "TU" after a QSO.
> Currently the F3 message is "TU".
> So I suggest changing ”TU" to "TU <my>".
> If you change the message, it will be the same as the real contest.
> I think it will be a good example for beginners.

I will mark Issue #381 as a duplicate of this Issue.

**Comment by w7sst** [comment]
I'd like to discuss and simple solution for this request. I like this idea and it would be easy to implement.

The question is how often to send this. In a pileup, sending "TU" is sufficient between callers in the Pileup, especially if you know there are multiple callers trying to call.

My suggestion...
- Perhaps we can send "TU \<my\>" every 3 or 4 calls.
- As Laurent pointed out above, the runner should send their call after at most 3 consecutive QSOs.
- Only send "TU \<my\>" in Pile-up or competition modes (not HST).

Options include:
1. send "TU \<my\>" every 3 or 4 calls. This can be implemented using `if Random < 0.33 then Send("TU <my>") else Send("TU");`
2. Implement a counter and count each QSO and send after 3 consecutive QSOs. This involves more work.
3. Derive a formula that looks at the Pileup count (# of active callers). When the pileup gets small, send the "TU \<my\>" again. This is the most complex option.

I think Option 1 using a Random number is the easiest to implement. Using 33% as the threshold results in send the call every 3 QSOs or so.

Thoughts?

Thank you,
Mike

@f6fvy @jr8ppg @K6OK @scotthibbs @WR7Q

**Comment by K6OK** [comment]
I have my N1MM configured to send TU <my> after every QSO, but that's my personal operating preference.  Regardless, if contesting etiquette and rules say every 3rd QSO, then MRCE should comply with that.  Option No. 1 sounds good to me.

**Comment by jr8ppg** [comment]
Hi, I agree with Mike's suggestion.

**Comment by w7sst** [comment]
Sounds good - I'll go with option 1.

Jim (@K6OK),
In the future, we could consider the following in the new GUI...
- add a switchbox in the new Settings dialog to enable/disable this feature.
- add an editable field to allow user to enter the details of their "TU" message. This would allow the user to enter "TU <my>" as their "TU" response string.

**Comment by w7sst** [comment]
Related Question...

Does the "F3" Key ('TU') also include this change, or only the "Enter" key behavior? My guess is that yes, we want both the Enter key and the F3 key behavior to be the same.

Thoughts?

TU and 73,
Mike

**Comment by f6fvy** [comment]
> Does the "F3" Key ('TU') also include this change, or only the "Enter" key behavior? My guess is that yes, we want both the Enter key and the F3 key behavior to be the same.

I don't think so. IMHO, the action of predefined F-keys should be predictable and remain the same in all cases.

**Comment by w7sst** [comment]
> I don't think so. IMHO, the action of predefined F-keys should be predictable and remain the same in all cases.

Thanks Laurent. I agree on keeping "F3" consistent in behavior. Therefore, this change will apply to "Enter" key only.

I coded up Option 1 (Random behavior at 33%) and I didn't like the feel of it. Too many occurrences of 4 to 5 QSOs without "TU \<my\>".

I have now added a counter to count subsequent QSOs since the last CQ and this feels much better and more consistent. It will generate "TU \<my\>" after 2 consecutive QSOs (every second QSO will get the extra 'TU \<my\>'). When a CQ is sent, the counter resets to zero.

We may decide that we want set the threshold to 3 instead of 2.

**Comment by f6fvy** [comment]
Another way would be to rely on the elapsed time between two "TU + myCall", which makes it independent of the CW speed and the operator skill.

**Comment by w7sst** [comment]
> Another way would be to rely on the elapsed time between two "TU + myCall", making it independent of CW speed and operator skill.

Good idea. what elapsed time do you recommend? 60, 90, 120 seconds?

**Comment by K6OK** [comment]
>> Does the "F3" Key ('TU') also include this change, or only the "Enter" key behavior? My guess is that yes, we want both the Enter key and the F3 key behavior to be the same.<<

MRCE seems to emulate N1MM's default settings for Enter Sends Message mode.  In N1MM ESM, the Enter key has no messages assigned to it, only sequences of F-keys.  Since Enter is going to fire F3 at the end of every QSO and logs it, then yes, the behavior should be the same.  

>>What elapsed time do you recommend? 60, 90, 120 seconds?<<

I don't see how that's going to work... if you're doing a short exchange like CQ WW at 40 wpm, 60 seconds is too long.  If you're doing Sweepstakes at 20 wpm, 60 seconds isn't long enough.  Just my opinion, I think MRCE should do the once-every-three QSOs for station ID because that's what the rules say.  We should be reinforcing good operating habits.  --  Jim

**Comment by jr8ppg** [comment]
> I think MRCE should do the once-every-three QSOs for station ID because that's what the rules say. We should be reinforcing good operating habits.

I agree with this opinion. I think this is a good practice for newcomers.

**Comment by w7sst** [comment]
Good input. Sounds good. Let's go with the once-every-three QSOs for station ID.

With this simple approach, perhaps we should also send the station ID in Single-Call mode as well. This will also help new users to learn these good operating habits.

**Comment by w7sst** [comment]
@jr8ppg has verified this Issue using the Code Review #385.

**Comment by w7sst** [comment]
I applied this change to the 1.85.2 branch yesterday. It turned out that this fix was integrated to main branch, not v1.85.2.
