### ISSUE TITLE
Windows Installer for MRCE

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#373]
## Summary
We need to create a Windows installer for MRCE. This will replace the current installation approach of placing the directory on the user's Desktop.

## Motivation
Modern applications have an installer. I think even the original Morse Runner 1.68 has an installer.

## Detailed Description
Self explanitory.

## Additional context
- We need to research the options and pick an installer package.
- We need to decide what installation options need to be provided (e.g. create Desktop shortcut).

## Tasks
- [ ] Collect requirements. This can be a discussion on this issue. If necessary, we can ask the question on the user's group.
- [ ] Pick installer.
- [ ] Development. Organize files in a separate subdirectory.
- [ ] Release notes and installation instructions. This will include pending changes to the MRCE homepage (to be published at release).
- [ ] Ask for volunteers to test the install image. Can be on this group or ask the user group for help.

**Comment by jr8ppg** [comment]
I created a prototype using Inno Setup 6.
Since writing to an INI file in the Program Files folder is not allowed, we need to modify MorseRunner to place the INI file in the AppData folder and read/write it from there.

ex.
C:\Users\<user name>\AppData\Roaming\MorseRunner\MorseRunner.ini

[MRCESetup.zip](https://github.com/user-attachments/files/21010322/MRCESetup.zip)

**Comment by jr8ppg** [comment]
**How to Get Inno Setup 6**

The following page serves as the main portal:
[https://jrsoftware.org/isinfo.php](https://jrsoftware.org/isinfo.php)

Click on **"Download Inno Setup"** to go to the download page:
[https://jrsoftware.org/isdl.php](https://jrsoftware.org/isdl.php)

Then download **`innosetup-6.4.3.exe`**.

Running **`innosetup-6.4.3.exe`** will start the installation process.

**Comment by jr8ppg** [comment]
**How to Build the Setup**

1. **Place the files as follows:**
<pre>
MorseRunnerSetup
    |
    +----\files(Input files)
    |       |
    |       +-- FDGOTA.txt
    |       +-- HstResults.txt
    |       +-- IARU_HF.txt
    |       +-- JARL_ACAG.TXT
    |       +-- JARL_ALLJA.TXT
    |       +-- K1USNSST.txt
    |       +-- MASTER.DTA
    |       +-- MorseRunner.exe
    |       +-- MorseRunner.ini
    |       +-- NAQPCW.txt
    |       +-- Readme.txt
    |       +-- SSCW.txt
    |       +-- ARRLDXCW_USDX.txt
    |       +-- CQWWCW.txt
    |       +-- CWOPS.LIST
    |       +-- DXCC.LIST
    |
    +----\Output
    |       |
    |       + MRCESetup.exe(This is the output file generated during the build.)
    |
    + MRCESetup.iss
</pre>

2. **Double-click** `MRCESetup.iss`.

3. Click **Build → Compile** from the menu.

4. `MRCESetup.exe` will be generated in the **Output** folder.

**Comment by jr8ppg** [comment]
![Image](https://github.com/user-attachments/assets/67c3bec4-e489-45d1-be6d-d92e4a2fd2a8)

**Comment by jr8ppg** [comment]
The current script is configured to place the INI file in the AppData folder.

ex)
C:\Users<user name>\AppData\Roaming\MorseRunner\MorseRunner.ini

**Comment by K6OK** [comment]
> I created a prototype using Inno Setup 6.

I took a look at Inno.  Excellent choice.  It is open source and Delphi-based.  Can't beat that!

One small difference: in my prototype I put the .ini file in AppData/Local not /Roaming.  I was under the impression that standalone desktop apps should use Local, while programs that support networked multiple devices use Roaming.  Probably doesn't matter.

73 Jim K6OK
@jr8ppg @w7sst
