### ISSUE TITLE
Wrap up v1.85.1 Bug Fix Release

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#375]
I'd like to release v1.85.1 before the end of the month. We had only one reported issue so far. Please let me know if you are aware of any other issues.

### Issues Resolved
- #370 
- Resolve 100-person limit on groups.io

### Tasks
- [x] Fix bug
- [x] (Mike) Write Release Notes (Readme.txt)
- [x] (@scotthibbs) [Review Release Notes](https://github.com/w7sst/MorseRunner/pull/374), make any changes, and approve (please update to readme-1.85.1 branch, not mainline)
- [x] (Mike) Create draft Release page. You can see it [here](https://github.com/w7sst/MorseRunner/releases)
- [x] (Scott) [Review](https://github.com/w7sst/MorseRunner/releases) draft Release page and make any changes.
- [x] (Mike) Post Release Candidate build for validation, including Bob, @WR7Q . Path to candidate build is [here](https://1drv.ms/u/c/353d3bde42947823/Ebwwvw5q1flGrwnnekXscI4Bxo47i_vvQF8jzfzC4DDnJg?e=Tmje3P).
- [x] (Mike) Final build, update Release image
- [x] (Mike) Post Release Image
- [x] (Mike) Post announcements on GitHub and groups.io
- [x] ~~(Mike) Notify ARRL Contest Update (the bi-weekly newsletter)~~
- [ ] (Frank, @W4Tg) Notify ARRL Affiliated Clubs through his contact
- [ ] (Jim, @K6OK ) add announcement to NCCC
- [ ] (Laurent, @f6fvy) add announcement on the European reflectors and groups.
- [x] (@jr8ppg) Posting in hamlife.jp
- [x] What am I missing?

**Comment by w7sst** [comment]
@scotthibbs @WR7Q @K6OK @W4Tg
Here is a path to the candidate build for 1.85.1. Please give it a spin and let me know if it seems like all is well.

Thank you for your help.
Mike W7SST

**Comment by K6OK** [comment]
Did testing with 1.85.1 for ARRL SS, WPX and K1USN.  It corrects the missing 'R'.  The three contests worked as expected for both Single Calls and Pileup modes.  No problems found.  --  Jim K6OK
@scotthibbs @WR7Q @K6OK @W4Tg

**Comment by scotthibbs** [comment]
Readme and draft release notes look great.

**Comment by W4Tg** [comment]
I’ve had no problems with the 1.85.1 release .

**Comment by w7sst** [comment]
I have posted the 1.85.1 bug fix release. Next step is to announce this release in our respective channels. After announcing, please check off the task (above) as complete.

Thank you again for all the help.

73, Mike

**Comment by w7sst** [comment]
Thank you for everyone who contributed to this release.

**Comment by W4Tg** [comment]
Hi Mike,
I'm wondering a couple of things:
1) Not much traffic on the groups.io channel - should I post questions such
as "What's next on the roadmap for MRCE?" which you or someone could
answer?  Or would you want to start a poll?
2) Is this year's open groups.io subscription all funded?
3) FD was a great accomplishment. Where do you want to take CE next?

Thanks,
Frank
W4TG

**Comment by K6OK** [comment]
Frank W4TG >> "What's next on the roadmap for MRCE?"

I'm making progress -- slowly but surely -- on the proposed next version, as described on the current roadmap and in [discussion 330](https://github.com/w7sst/MorseRunner/discussions/330).  The beta, as it currently stands, is not in a useable state that can be shared with the group at the moment.   

Low traffic on the reflector might be a good thing if it means people are figuring out how to use the program on their own and aren't experiencing bugs :-)   73 Jim K6OK

@w7sst @W4Tg

**Comment by W4Tg** [comment]
Jim,
I haven't downloaded the P release, but I will and will comment back.  It
looks like everyone is pretty pleased with it.
Yes, low traffic could mean "no complaints," or possibly "low usage of new
features."  I, and others spread the word about the Nov SS release but we
probably didn't hit everyone.  For next year, perhaps ARRL will provide a
pointer to it.   The contest committee is investigating how to get greater
participation, and for CW, MRCE might help prepare hams that wouldn't
normally operate it.

2 thoughts I had recently:
-Is it possible to have a personal scoreboard, a la RufzXP, showing one's
previous contest, duration, and score?  I do this in a notebook today, but
it would be nice to have it available within MRCE.
-Also, when I operated the 10M contest this year, I realized that MRCE
didn't have that contest, but was able to train for it via existing
contests WPX (for serial numbers) and ARRL DX (for state/province).
Therefore, I don't think it requires the exact contest for skills training,
although some may differ in their assessment.

- frank W4Tg

**Comment by K6OK** [comment]
Frank -- I also spent a little bit of time in the 10m contest.  Just now I looked at ARRL's website and the 10m contest has received 6,411 logs -- that's huge, I had no idea 10m contest was so popular!  That makes it probably the world's 3rd most popular contest behind CQ WW CW and SSB.  So yes I would also advocate MRCE supporting ARRL 10m.

I also agree with you that down the road MRCE could consider an enhancement with a report that would show a record of the user's progress with name of contest, CW speed, score and error rate.   73 Jim K6OK   @W4Tg @w7sst

**Comment by W4Tg** [comment]
Jim,
Probably due to sunspot cycle peak! But maybe next year too if we get a
double peak.

73,
Frank
W4Tg

**Comment by w7sst** [comment]
> 2) Is this year's open groups.io subscription all funded?

Hi Frank,
- groups.io was funded for a year. $220 paid for hosting in October. Hosting fee is paid through Nov 2025.
- Our current balance is $70 and slowly growing.
- Group membership has grown to 142 members.

Also, I have been working on a few bugs and getting ready to release another bug fix release 1.85.2. I will post a review copy in the next few days. Then I can get back to helping Jim with the new GUI.

Merry Christmas and Happy New Year...

73,
Mike W7SST ..

**Comment by W4Tg** [comment]
Jim,
I played a bit with the P Version, mostly to see your changes.  Nice job.
I'm glad for the Pause button and the RIT label.  The Activity will need
more context until it is meaningful.  Have you or others had discussion
with the CWA Instructors or club instructors as to what they would want for
training?
Regarding the 8 vs. 12 function keys, I typically customize the extra ones
in N1MM per contest for selective fills, e.g., in SS,  Sec?  or Pr? That
would require programming on the response side for SAC, SCV etc.  Were you
thinking of adding that?

I see that the window isn't sizable and you've made the p window bigger,
which is fine on my machine - I don't know if that would cause problems for
anyone else.

Let me know if I missed something that you wanted feedback on.
73,
Frank
 @K6OK @w7sst

(Also, it's faster for me to respond in email than github, but if it is
easier for you, let me know)

**Comment by K6OK** [comment]
Frank -- Thanks for your review and input, glad you like the Pause and RIT label.

- Activity: getting this feature working with input from the training community is planned
- 12 F keys: having the ability to customize the message sent by contest in a similar way to N1MM's .mc files would be a nice enhancement but is not planned to be part of what I'm working on.
- Window sizing.  Fixed form sizes are common for niche Windows programs because it's easier and faster to develop them that way.  A display setting of 96 dpi and 100% is assumed and it works for most users.  Some laptops use 125% or 150% scaling so will need to test the program for that scenario.  Updating MRCE to be fully resizable as well as being "DPI aware" and "scaling aware" with automatic resizing of fonts and controls would require a major re-design.

Right now my focus are proposed changes to how Settings are handled and also user management of History files.  Stay tuned...    73 Jim K6OK 
@W4Tg @w7sst
