### ISSUE TITLE
Add maximize button

### ISSUE THREAD

**Issue by scotthibbs** [w7sst/MorseRunner#377]
## Summary

Now that we have a minimize button, it would be nice to have the program have a maximize button. This will be very helpful to those who have trouble seeing. 

This would entail having to reformat the different sections so that it would display correctly. 

## Motivation

 This is a normal function of a modern windows program.

## Detailed Description

The normal maximize button at the top of the form of the program. 
## Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, I'm available to discuss possible solutions and alternatives to this problem.
- [x] Yes, I'd like to review and provide feedback on the proposed solution.
- [x] Yes, I'm available to help test a solution to this problem.

## Tasks
- [ ] Coding and integration
- [ ] Validation

**Comment by K6OK** [comment]
Scott: Good comment to consider the visually impaired.  A few thoughts on this --

Is Maximize still "modern"?  A user with an ultrawide curved 5120 x 1440 monitor, are they going to maximize MRCE all they way across?  If I had to guess as these monitors become increasingly common Maximize will become less important but user-definable resizing and positioning will be a must-have.

Windows accommodates the visually impaired under Accessibility/Ease of Access primarily with scaling, making everything on the desktop be magnified by 125%, 150%, etc.  I don't believe Windows recommends Maximize as a strategy for the vision impaired.  I think what should be done, if it hasn't been done already, is to check MRCE to make sure it's readable and useable at 125% and 150% scaling.  This is a good thing to check for laptop users too.  

Three applications I use frequently -- N1MM, DXLab Suite, and PuTTY -- do not have Maximize enabled.  I think it's okay to continue as a fixed size application for now, it's not like MRCE is the only one.

I do think as a long-term enhancement it might be worthwhile to consider a "Phase II GUI enhancement" that allows the user to resize the form, panels with handles that can slide, user choice of fonts/font sizes, etc.  MRCE currently has 12 panels that interact with each other in a complicated way so undoing all that would be IMHO a significant coding effort.

73 Jim K6OK
@scotthibbs @w7sst

**Comment by scotthibbs** [comment]
Thanks for the comments Jim. 

I use five different computers during the day. This laptop for my recliner. I have a laptop for my piano. I have a laptop on my big screen tv. In my shack/office have a laptop for my Flex Radio which has three extra screens on it. My main desktop has three big screens. I'm always resizing/moving windows programs around to fit. 

The maximize button is for my laptop (while I'm in my recliner). Honestly there is no reason for me to see the desktop while using MRCE, I highly doubt anyone is multitasking with it. The only exception to this would be N1MM. Honestly, I'd rather see the 2009 Windows 7 function of [Win]+[arrows] to move the program around which would include maximize [Win]+[up arrow]. 

You mentioned DXLab Suite and it's a sore spot for me. I made several suggestions and coding fixes over a decade that were completed for me, but when I asked for a maximize button and/or the 2009 Windows 7 movable windows functions, I got criticized.  (It also had a work-around for those with multiple monitors if it dissapeared on a removed screen instead of modernizing with windows versions.) So I pointed out that the program reshapes itself wildly depending on what view is selected and if you go through those selections rapidly it flops on the screen like a fish. I actually did a Youtube video of these issues and how it can get lost with multiple monitors or displaying off screen. However, I got moderated (and rightly so) for saying that without these features it looked like it was written for the Commodore 64. LOL..  So I moved on to a "modern" logging with N3FJP and couldn't be happier because it's a true "windows" program. 

Hard to believe but Putty is 25 years old too - first used in Win98 or Win 2000. And I'd like to point out, once logged in with Putty, you absolutely have a maximize button for the terminal... I guess I do maximize a lot. :)  

I like the "phase 2 GUI enhancement idea".. That would be cool. I know you got a 1.90 GUI change in the works (I'm a big fan of that too) could it get the 2009 Windows 7 win key and arrows moving functions with the new 1.90 GUI? Really brings programs into the modern windows age. 

PS. I have a friend who is a blind ham who learned CW as a kid. I need to make contact with him and have him check out MRCE for his feedback.
