### ISSUE TITLE
Wrap up v1.85.2 Bug Fix Release

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#389]
I'd like to release v1.85.2 in the next week or two. There were a few additional bugs that I wanted to fix before switching over to help Jim with the new GUI. There was also talk of a new contest. For now, I wanted to fix these quality and behavior issues.

### Issues Resolved
- #247
- #353 
- #382 
- #379 
- #290 
- #390 
- #394 
- #382
- #399
- #326 
- #403 
- #404 
- #405 
- #406 
- #407 
- #408 
- #413 
 
### Tasks
- [x] Fix bugs
- [x] (Mike) Write Release Notes (Readme.txt)
- [x] (Mike) Create draft Release page. You can see it [here](https://github.com/w7sst/MorseRunner/releases)
- [x] (Scott) [Review](https://github.com/w7sst/MorseRunner/releases) draft Release page and make any changes.
- [x] (Mike) Post Release Candidate build for validation. Path to latest preliminary build is [here](https://1drv.ms/u/c/353d3bde42947823/Eds6D6xMJfJEnTVVaK11L48BbPGJ1cC8VlqiHqIkQ4WFHg?e=1ZchMZ). Updated Mar 5, 2025.
- [x] (Mike) Add 3 remaining issues to Readme.txt file and post a code review for Scott.
- [x] Updated ARRL DX Call History File
- [x] (Mike) Fix #399
- [x] (Mike) Fix #326
- [x] (Mike) Final build, update Release image
- [x] (Mike) Post Release Image
- [x] (Mike) Post announcements on GitHub and groups.io
- [x] What am I missing?

**Comment by w7sst** [comment]
@scotthibbs @k6ok @WR7Q @f6fvy @jr8ppg

**Comment by w7sst** [comment]
[Here](https://1drv.ms/u/c/353d3bde42947823/ESo_Lc1fIANEs17FISbqUdgBhkBoW2XUHKuU8HnxUijPkg?e=ojm9zV) is the final image to be released. I have started all contests and work a few QSO in several of them. I don't see any other bugs that should be fixed in this bug fix release. I'm hoping to post/announce this release on Tuesday afternoon.

73,
Mike

@scotthibbs @k6ok @WR7Q @f6fvy @jr8ppg

**Comment by w7sst** [comment]
Well, that didn't happen. Looks like this will go out in January sometime, perhaps by the 15th.

**Comment by w7sst** [comment]
I have fixed Issue #379. This hang was caused randomly when using the QRM Band Condition. The program would go into an endless loop and freeze the UI.

I'm now targeting Feb 28th as a new release date for 1.85.2.

[Here is a link](https://1drv.ms/u/c/353d3bde42947823/EQUWgGpSZ4ZGpjWW1qvwpqIBJtRAigdclMzJcRd0GbHGwA?e=0P3x1h) to the latest `v1.85.2` build.

If you have some time, please give this a try.  

73, Mike W7SST

**Comment by f6fvy** [comment]
Just a small remark : ARRLDXCW_USDX.txt has 3 bad entries where the exchange isn't part of the 48 continuous states, that are required for the ARRL DX Contest :

Line 5089 K9FD,MERV,HI,
Line 10038 N6VUY,,PR,
Line 14016 W3ARS,,FS,  <-- ???

**Comment by w7sst** [comment]
> Just a small remark : ARRLDXCW_USDX.txt has 3 bad entries where the exchange isn't part of the 48 continuous states, that are required for the ARRL DX Contest :
> 
> Line 5089 K9FD,MERV,HI, Line 10038 N6VUY,,PR, Line 14016 W3ARS,,FS, <-- ???

Hi Laurent,
Thanks for letting me know about this. I downloaded the latest ARRL DX call history file (ARRLDXCW_USDX-2026.txt). I made a few manual changes to this new file to address the concerns that you noted above. 

Sorry I didn't address this a few months ago and get a bug-fix release out. I need a better tracking system for regular updates with update call history files.

As always, thank you for all your help!

73, Mike

@f6fvy

**Comment by w7sst** [comment]
@jr8ppg 

Do you have any call history files that you would like to update for this upcoming release?

Tnx.

**Comment by jr8ppg** [comment]
@w7sst 

There are no updates this time.
Thank you.

**Comment by scotthibbs** [comment]
I ran the release image and loved it. I wasn't doing any extensive testing but I usually only capture the first two letters of a call. Previously, I just waited until I got more but now I am able to send the two letters and everyone waits their turn. Fantastic! 

I looked at the release notes draft and it is perfect.

**Comment by w7sst** [comment]
Awesome. Glad you like the improved partial call matching.

I will try to get this out the door sometime this week. Please feel free to mark any of the above issues as "Verified" (or let me know which ones to updated). I will eventually close them all.

73, Mike

**Comment by w7sst** [comment]
Scott and others...

[Here is a link to v1.85.2-rc1](https://1drv.ms/u/c/353d3bde42947823/ETzKCyiRwspLqj5ofycoMNoBCVH1LLVjCOmqNmoSi2E5-A?e=Vzb9yc). After expanding this onto your Desktop, you can copy in your previous `MorseRunner.ini` file into the new directory.

If you can do some testing with this, I would appreciate it. Please try to exercise several contests so we can make sure they are all working.

Thank you and 73,
Mike

**Comment by w7sst** [comment]
Thank you to everyone who helped on this release. I appreciate all the help with code reviews and the good ideas from everyone.

73,
Mike W7SST
